# Site Settings
title: "Kevin.exe - Cybersecurity Journey"
description: "5-Year SANS-Equivalent Self-Study: From CS Student to Security Expert"
url: "https://KevinEinWindir.github.io"
baseurl: ""

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"  # Changed to dark theme

# Site Author
author:
  name: "Kevin"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "CS Student → Security Expert | Documenting my SANS-equivalent cybersecurity journey"
  location: "United States 🇺🇸"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KevinEinWindir"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "#"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your.email@example.com"

# Additional settings for better styling
teaser: "/assets/images/default-teaser.jpg"
logo: "/assets/images/logo.png"
masthead_title: "Kevin.exe"

# Search
search: true

# Comments
comments:
  provider: "disqus"
  disqus:
    shortname: "your-disqus-shortname"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "your-tracking-id"
